[package]
name = "gadgetry-most-foul"
description = "Expose standard or fully custom USB peripherals (gadgets) through a USB device controller (UDC) on Linux."
categories = ["hardware-support", "os::linux-apis"]
keywords = ["usb", "gadget", "peripheral", "configfs", "functionfs"]
license = "Apache-2.0"
repository = "https://github.com/samcday/gadgetry-most-foul"
authors = ["gadgetry-most-foul authors"]
rust-version = "1.88"
exclude = [".cargo/", ".github/", ".misc/", ".vscode/"]
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
async-io = "2"
bitflags = "2.4"
byteorder = "1"
futures = { version = "0.3", default-features = false, features = ["std"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
libc = "0.2"
log = "0.4"
macaddr = "1.0"
rustix = { version = "1", features = ["fs", "mount", "event", "system", "time"] }
proc-mounts = "0.3"
slab = "0.4"
strum = { version = "0.28", features = ["derive"] }
uuid = "1"

[dev-dependencies]
dma-buf = "0.5"
dma-heap = "0.4"
env_logger = "0.11"
nusb = "0.2"
serial_test = "3"
tempfile = "3"
tokio = { version = "1", features = ["macros", "net", "rt", "sync", "time"] }

[[example]]
name = "custom_interface_device_async"
doc-scrape-examples = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]
